[package]
name = "xr-proto"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
base64 = "0.22"
rand = "0.8"
tracing = "0.1"
